apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-config"
data:
  SPRING_DATASOURCE_URL: "{{ .Values.properties.datasource.url }}"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "{{ .Values.properties.kafka.servers }}"
  SPRING_CACHE_REDIS_TIME_TO_LIVE: "{{ .Values.properties.redis.ttl }}"
  SPRING_DATA_REDIS_HOST: "{{ .Values.properties.redis.host }}"
  SPRING_DATA_REDIS_PORT: "{{ .Values.properties.redis.port }}"
  SPRING_APPLICATION_NAME: "{{ .Values.properties.app.name }}"
  SERVICE_CATEGORY_SERVICE_NAME: "{{ .Values.properties.app.categoryService.name }}"
  MINIO_BUCKET: "{{ .Values.properties.minio.bucket }}"