apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Chart.Name }}"
spec:
  replicas: "{{ .Values.replicaCount }}"
  selector:
    matchLabels:
      app: "{{ .Chart.Name }}"
  template:
    metadata:
      labels:
        app: "{{ .Chart.Name }}"
    spec:
      containers:
        - name: "{{ .Chart.Name }}"
          image: "{{ .Values.image.tag }}:{{.Values.image.version}}"
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: "{{ .Chart.Name }}-secret"
            - configMapRef:
                name: "{{ .Chart.Name }}-config"