apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Chart.Name }}-secret"
type: Opaque
stringData:
  MINIO_ENDPOINT: "{{ .Values.properties.minio.endpoint }}:{{ .Values.properties.minio.port }}"
  MINIO_USERNAME: "{{ .Values.properties.minio.username }}"
  MINIO_PASSWORD: "{{ .Values.properties.minio.password }}"
  SPRING_DATASOURCE_USERNAME: "{{ .Values.properties.datasource.username }}"
  SPRING_DATASOURCE_PASSWORD: "{{ .Values.properties.datasource.password }}"