apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}-service"
spec:
  type: NodePort
  selector:
    app: "{{ .Chart.Name }}"
  ports:
    - port: "{{ .Values.properties.app.port }}"
      targetPort: 8080