apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.service.name }}"
spec:
  type: NodePort
  selector:
    app: "{{ .Release.Name }}"
  ports:
    - port: "{{ .Values.service.port }}"
      targetPort: 8080