apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-app-config
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://catalog-postgres-service:5433/catalog_service
  SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka-0.kafka-service:9092
  SPRING_CACHE_REDIS_TIME_TO_LIVE: "1d"
  SPRING_DATA_REDIS_HOST: catalog-redis-service
  SPRING_DATA_REDIS_PORT: "6380"
  SERVICE_PRODUCT_CATEGORY_URL: http://category-service:8080
  MINIO_BUCKET: products