apiVersion: v1
kind: Service
metadata:
  name: catalog-postgres-service
spec:
  selector:
    app: catalog-postgres
  ports:
    - port: 5433
      targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-redis-service
spec:
  selector:
    app: catalog-redis
  ports:
    - port: 6380
      targetPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-app-service
spec:
  type: NodePort
  selector:
    app: catalog-app
  ports:
    - port: 8081
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-minio-service
spec:
  selector:
    app: catalog-minio
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
  type: ClusterIP