apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}-service"
spec:
  type: ClusterIP
  selector:
    app: "{{ .Chart.Name }}"
  ports:
    - port: {{ .Values.properties.application.port }}
      targetPort: 8080